flesh out validate script

diff --git a/bin/validate b/bin/validate
--- a/bin/validate
+++ b/bin/validate
@@ -6,8 +6,25 @@ var Path = require('path');
 var Utils = require('../lib/utils');
 
 var internals = {
-    pathSep: process.platform === 'win32' ? ';' : ':'
+    pathSep: process.platform === 'win32' ? ';' : ':',
+    longest: 0
 };
+
+if ((process.stdout &&
+     process.stdout.isTTY) ||
+     process.platform === 'win32' ||
+     process.env.COLORTERM ||
+     /^screen|^xterm|^vt100|color|ansi|cygwin|linux/i.test(process.env.TERM)) {
+
+    internals.failed = '\x1B[31mfailed!\x1B[39m';
+    internals.passed = '\x1B[32mok\x1B[39m';
+    internals.missing = '\x1B[33mn/a\x1B[39m (no script found)';
+}
+else {
+    internals.failed = 'failed!';
+    internals.passed = 'ok';
+    internals.missing = 'n/a (no script found)';
+}
 
 
 // Create a copy of process.env, with the PATH environment variable
@@ -33,18 +50,27 @@ internals.getEnv = function (projectRoot) {
 // Actually run the given script for the given project
 internals.runCmd = function (projectRoot, env, name, script, done) {
 
-    done = done || process.exit;
-    process.stdout.write('running ' + name + ': ');
+    done = internals.tasks.length ? internals.tasks.shift() : process.exit;
+    var pad = '';
+    for (var i = 0, il = internals.longest - name.length; i < il; ++i) {
+        pad += ' ';
+    }
 
+    if (!script) {
+        console.log('running %s: %s%s', name, pad, internals.missing);
+        return internals.exit(0, done);
+    }
+
+    process.stdout.write('running ' + name + ': ' + pad);
     var cmd = (process.platform === 'win32' ? 'cmd /c ' : 'sh -c ') + JSON.stringify(script);
     Exec(cmd, { cwd: projectRoot, env: env }, function (err, stdout, stderr) {
         if (err) {
-            console.log('failed!');
+            console.log(internals.failed);
             console.log(stdout);
             console.log(stderr);
             internals.exit(err.code, process.exit);
         } else {
-            console.log('ok.');
+            console.log(internals.passed);
             internals.exit(0, done);
         }
     });
@@ -82,6 +108,8 @@ internals.exit = function (code, callback) {
 var hook = Path.basename(process.argv[1]);
 var projects = Utils.findProjects();
 
+internals.tasks = [];
+
 for (var i = 0, il = projects.length; i < il; ++i) {
     var project = projects[i];
 
@@ -90,22 +118,30 @@ for (var i = 0, il = projects.length; i < il; ++i) {
     var pkg = require(Path.join(project, 'package.json'));
     var scripts = pkg[hook] || config[hook] || [];
 
+    if (scripts.length) {
+        if (il > 1) {
+            console.log('running %s checks for %s...', hook, Path.basename(project));
+        }
+        else {
+            console.log('running %s checks...', hook);
+        }
+    }
+
     var tasks = [];
 
     for (var m = 0, ml = scripts.length; m < ml; ++m) {
         var script = scripts[m];
-        var command = (pkg.scripts || {})[script] || (config.scripts || {})[script];
-        if (command) {
-            var task = internals.runCmd.bind(null, project, env, script, command);
-            tasks[m] = function () {
+        var command = (pkg.scripts || {})[script] || (config.scripts || {})[script] || '';
+        internals.longest = (internals.longest < script.length) ? script.length : internals.longest;
 
-                task.call(null, tasks[i + 1]);
-            };
-        }
+        var task = internals.runCmd.bind(null, project, env, script, command);
+        tasks[m] = task;
     }
 
-    if (tasks.length) {
-        console.log('Running %s checks for %s...', hook, Path.basename(project));
-        tasks[0]();
-    }
+    internals.tasks = internals.tasks.concat(tasks);
+}
+
+if (internals.tasks.length) {
+    var task = internals.tasks.shift();
+    task();
 }
